### ISSUE TITLE
增加自定义指令

### ISSUE THREAD

**Issue by NY1200NY** [alazeprt/AQQBot#23]
# 功能1 (no want)
增加自定义指令，如在群里发送```购买 {gift-name} [count]```
机器人发送 ```是否购买 {count} 个 {gift-name} ? ```
玩家在群里发送 ```是/否    Y/N``` 【可在配置文件中自定义】
:::tip 提示
其中{gift-name} [count] 可在配置文件中自定义
:::
And more

# 功能2 (want)
所有自定义指令可在```custom.yml```中编辑(新创文件)
For example:
```YAML
enable: false
custom:
    example1:
        group: "你好"
        server: "[Console]say hello" #use console
        server: "[OP]say hello" #检查群里发消息的玩家的群名片名称的游戏玩家，以他的身份执行此条命令
        #上面两个server任选其一
        #配置许多，单一列举
```
